In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)  #通过np.array将python基本数组转换为ndarray对象
                        #np.array接受一切序列型的对象
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.ndim #ndim函数用于输出维度

2

In [5]:
arr2.shape

(2, 4)

In [6]:
arr1.dtype
arr2.dtype

dtype('int32')

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((3,6,5))  #np.zeros用于创建多维全零矩阵

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [9]:
np.empty((2,3,2))   #np.empty返回一些未初始化的垃圾值

array([[[1.16449042e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.69693424e+184]],

       [[3.95488540e+179, 1.05845945e+165],
        [7.87247761e-067, 2.83181462e-056],
        [1.03034878e-071, 6.09989430e+170]]])

In [10]:
type(np.zeros(10))

numpy.ndarray

In [12]:
npa = np.arange(15)
print(type(npa))  #python自带range(n)函数的数组版就是np.arange(n) 从0到n-1
npa

<class 'numpy.ndarray'>


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64) #np.astype可以改变数据类型
print(float_arr.dtype)

int32
float64


In [15]:
n_strings = np.array(['12','34','5.6'],dtype = np.string_)
print(n_strings.dtype)

|S3


In [18]:
n_float64 = n_strings.astype(np.float64)  #astype可以将只有数字的string_类型直接变为数值类型0.0
print(n_float64)
print(n_float64.dtype)

[12.  34.   5.6]
float64


In [19]:
#大小相等的数组之间的任何算数都会运用到对应位置上去
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr)
print(arr * arr)
print(arr - arr)
#数组对进行算数运算会对每个位置进行该算术运算
print(1/arr)
print(arr ** 0.5)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [21]:
#通过直接取索引可以直接获取某位置上的值
arr = np.arange(10)
a = arr[5]
a

5

In [22]:
#通过索引可以直接取区间内容
a1 = arr[5:8]
a1

array([5, 6, 7])

In [24]:
#如果直接对用索引取出的对象赋值 则会直接改变原对象的值 因为通过索引取出的是原始数组的视图而非副本
#不过如果将其赋值给一个对象 那便成为了副本 对其修改不会影响原有对象
arr[5:8] = 12
print(arr)
a1 = arr[4:8]
a1 = 10
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]
[ 0  1  2  3  4 12 12 12  8  9]


In [25]:
#使用冒号取切片 规则是使用的是从0开始的索引 而且左闭右开
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[:2]#从头到2 2不取 则是0 1


array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr2d[:2,1:] #首先只选取0和1位置的元素 对于0和1位置的元素而言 每个里面再取从1到结束 得到如下结果

array([[2, 3],
       [5, 6]])

In [32]:
arr2d1 = arr2d[:2]
print(arr2d1)
print(arr2d1.shape)
print(arr2d1[1:])
print(arr2d1[1:].shape)
print(arr2d.shape)
print(arr.shape)
#通过冒号：的切片 最终得到的维度和之前是一样的
#而且如果分两步进行切片和用逗号隔开的两个切片是不同的（和上面的arr2d[:2,1:]对比）

[[1 2 3]
 [4 5 6]]
(2, 3)
[[4 5 6]]
(1, 3)
(3, 3)
(10,)


In [33]:
print(arr2d[1,:2])
print(arr2d[1,:2].shape)
#通过整数而非冒号取视图的话 会将维度改变

[4 5]
(2,)


In [38]:
names= np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.17238805  1.89101965 -1.18038443 -0.94231234]
 [ 0.73235191  1.57457657  0.62062599  1.87533375]
 [ 1.55254021  0.69845284 -1.21091038 -0.14065079]
 [-1.16284019  0.52156827 -2.55895719  1.36138013]
 [ 0.59249751 -0.01725452  0.8634446   1.28711736]
 [-2.79481486 -0.62876795  0.96931379 -0.6202353 ]
 [ 0.13378531  0.12503204  1.2669337   0.10910239]]


In [39]:
names == 'Bob'  #==运算同样地适用于数组矢量运算

array([ True, False, False,  True, False, False, False])

In [40]:
data[names=='Bob'] #可以直接用布尔数组作为索引进行取值

array([[ 0.17238805,  1.89101965, -1.18038443, -0.94231234],
       [-1.16284019,  0.52156827, -2.55895719,  1.36138013]])

In [41]:
data[names == 'Bob', 2:] #得到的结果是二维数组说明布尔序列和:一样 都不会改变维度 而：从本质上看也是序列 所以序列类型作为索引不会改变维度

array([[-1.18038443, -0.94231234],
       [-2.55895719,  1.36138013]])

In [42]:
#花式索引 通过整数数组进行索引 这种索引将矩阵进行了重排列 结果的顺序和之前的所有方法都不同
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [43]:
arr[[4,6,1,2]]  #可以通过整数数组取序列

array([[16, 17, 18, 19],
       [24, 25, 26, 27],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
#一次传入多个索引数组的情况
arr[[1,5,7,2,],[0,3,1,2]] #得到的是(1,0)。。。。位置的元素

array([ 4, 23, 29, 10])

In [45]:
#如果想要按照第一个数组取行 第二个数组取列的方法进行
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [46]:
arr[[1,5,7,2]][:,[0,3,1]]

array([[ 4,  7,  5],
       [20, 23, 21],
       [28, 31, 29],
       [ 8, 11,  9]])

In [47]:
#或者使用np.ix_方法 将两个一维数组转化为方形阵索引器
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [48]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
arr.T #T可以直接进行转置运算

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [50]:
np.dot(arr.T,arr) #这就是ATA 矩阵内积

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [51]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,False,True,True])

In [52]:
result = np.where(cond,xarr,yarr) #np.where函数 用于通过判断语句 在两种内容之间选择 类似于if condition x else y
result

array([1.1, 2.2, 2.3, 1.4, 1.5])

In [54]:
arr = np.random.randn(4,4)
arr

array([[-1.25263085, -1.59739201, -2.46124797, -0.08458325],
       [ 1.42475752,  1.38320275,  1.06728213,  1.03039615],
       [ 0.76828658, -1.97414008, -0.09702524,  1.45860246],
       [ 0.58870136,  0.93281899,  0.16322342,  0.85165956]])

In [55]:
np.where(arr>0,2,arr)  #通过判断 直接将大于0的部分变为2

array([[-1.25263085, -1.59739201, -2.46124797, -0.08458325],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        , -1.97414008, -0.09702524,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ]])

In [56]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [57]:
arr.cumsum(0)  #所有元素累计和 （按列取）

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [59]:
arr.cumsum(1)  #所有元素累计和 （按行取）

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [60]:
arr.cumprod(0) #所有元素累计积 （按列）

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]], dtype=int32)

In [58]:
arr.cumprod(1) #所有元素累计积 （按行）

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [61]:
arr = np.random.randn(100)
(arr>0).sum()  #sum函数用于对布尔数组的True值的统计

40

In [62]:
bools = np.array([False, False, True, False])
print(bools.any())  #是否存在任何一个True any的概念
print(bools.all())  #是否所有都是True all的概念

True
False


In [63]:
names= np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)  #唯一化

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [64]:
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])  #in1d用于计算一个对象的每个元素是否在一维集合中 

array([ True, False, False,  True,  True, False,  True])

In [66]:
values = np.arange(32).reshape(4,8)
values

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [67]:
np.in1d(values,[1,2,3])

array([False,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])