In [1]:
import numpy as np

In [ ]:
'''
ndarray对象由以下部分组成：
1.一个指向数组内存的指针
2.数据类型dtype
3.一个表示数组形状的元素shape
4.一个跨度元素stride 其中的整数指的是为了前进道当前维度的下一个元素需要“跨过”的字节数
'''

In [2]:
np.ones((10,5)).shape

(10, 5)

In [5]:
print(np.ones((3,4,5),dtype=np.float32).strides)
np.ones((3,4,5),dtype=np.float64).strides

(80, 20, 4)


(160, 40, 8)

In [4]:
np.float64.mro()
#使用mro可以看到所有的父类（继承关系）
#numpy.floating和numpy.integer是比较有代表性的下层子类

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [8]:
ints = np.ones(10,dtype=np.int16)
floats = np.ones(10,dtype=np.float32)
print(np.issubdtype(floats.dtype,np.floating))
np.issubdtype(ints.dtype,np.integer)
#使用issubdtype可以判断是否为某种类型的子类

True


True

In [9]:
#高级数组操作

In [10]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [12]:
arr = np.arange(15)
arr.reshape((5,-1))
#可以给一维提供-1 由计算获得

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
arr = np.arange(15).reshape((5,3))
arr.ravel()
#reshape的逆运算可以是ravel 散开操作 将其拉成一维

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
arr = np.arange(15).reshape((5,3))
print(arr.flatten())
arr
#flatten同ravel不过它返回的是数据的副本 没有改变原对象

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
#数组的合并与拆分
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
np.concatenate([arr1,arr2],axis=1)
#拼接 可以按照两个维度进行拼接
#pandas有merge和concat 当然concat和这个concatenate类似

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [19]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [21]:
arr = np.random.randn(5,2)
arr

array([[ 0.1245938 , -1.22631231],
       [-0.11870601, -1.30076456],
       [-0.59005879, -0.48616639],
       [-0.46487556,  1.50984363],
       [-2.01911063, -1.25730707]])

In [26]:
first,second,third = np.split(arr,[1,3])
first
#split则是用来进行拆分的

array([[ 0.1245938 , -1.22631231]])

In [27]:
arr = np.arange(3)
arr.repeat(3)
#repeat方法可以对内容进行重复 如果传入的是单参数 则重复该次

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [31]:
arr.repeat([2,3,4])
#如果传入的是和原数组维度完全相同的一个数组 则按照对应关系重复该次数

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [32]:
arr = np.random.randn(2,2)
arr

array([[ 0.4247215 , -0.74791516],
       [ 0.6630086 , -0.47410344]])

In [33]:
arr.repeat(2,axis=0)

array([[ 0.4247215 , -0.74791516],
       [ 0.4247215 , -0.74791516],
       [ 0.6630086 , -0.47410344],
       [ 0.6630086 , -0.47410344]])

In [34]:
arr.repeat(2,axis=1)

array([[ 0.4247215 ,  0.4247215 , -0.74791516, -0.74791516],
       [ 0.6630086 ,  0.6630086 , -0.47410344, -0.47410344]])

In [35]:
arr.repeat(2) #如果不显式设置轴向 则数组会扁平化 所以还是要显式设置轴向

array([ 0.4247215 ,  0.4247215 , -0.74791516, -0.74791516,  0.6630086 ,
        0.6630086 , -0.47410344, -0.47410344])

In [38]:
print(arr)
np.tile(arr,2)
#放在一起显示很明显 tile是进行堆叠数组的行为 参数设置堆叠次数

[[ 0.4247215  -0.74791516]
 [ 0.6630086  -0.47410344]]


array([[ 0.4247215 , -0.74791516,  0.4247215 , -0.74791516],
       [ 0.6630086 , -0.47410344,  0.6630086 , -0.47410344]])

In [39]:
np.tile(arr,(2,1))

array([[ 0.4247215 , -0.74791516],
       [ 0.6630086 , -0.47410344],
       [ 0.4247215 , -0.74791516],
       [ 0.6630086 , -0.47410344]])

In [40]:
np.tile(arr,(3,2))
#纵向叠三次 横向叠两次

array([[ 0.4247215 , -0.74791516,  0.4247215 , -0.74791516],
       [ 0.6630086 , -0.47410344,  0.6630086 , -0.47410344],
       [ 0.4247215 , -0.74791516,  0.4247215 , -0.74791516],
       [ 0.6630086 , -0.47410344,  0.6630086 , -0.47410344],
       [ 0.4247215 , -0.74791516,  0.4247215 , -0.74791516],
       [ 0.6630086 , -0.47410344,  0.6630086 , -0.47410344]])

In [41]:
print('###############################################################')
#广播 broadcasting

###############################################################


In [42]:
arr = np.arange(5)
arr*4
#此时可以说 标量4被广播到了其他所有元素上

array([ 0,  4,  8, 12, 16])

In [43]:
arr = np.random.randn(4,3)
arr.mean(0)

array([ 0.47680447, -0.09675732, -0.48885988])

In [44]:
demeaned = arr-arr.mean(0)
demeaned
#此时同样地 一个(4,3)维度的和一个(3,)维度的运算 按照行广播了下去

array([[-0.02446068,  0.11018126,  0.55700579],
       [-1.19853582,  0.24570388,  0.95468313],
       [ 1.103189  ,  0.23953676, -0.54913896],
       [ 0.1198075 , -0.5954219 , -0.96254996]])

In [47]:
row_means = arr.mean(1)
row_means.reshape((4,1))
demeaned1 = arr-row_means.reshape(4,1)
demeaned1
#此样例是按照列进行广播下去 所以必须保证被广播的对象是和每列对象同维度的

array([[ 0.27437258, -0.16454727, -0.1098253 ],
       [-0.6860775 ,  0.18460041,  0.50147709],
       [ 1.35173545, -0.08547859, -1.26625686],
       [ 1.112271  , -0.17652019, -0.93575081]])

In [ ]:
#如果使用arr-row_means是报错的 因为被广播的维度是(4,)而非(4,1)
#可见 需要添加一维新轴才能使其被广播出去

In [52]:
arr = np.zeros((4,4))
arr3d = arr[:, np.newaxis, :]
arr3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [53]:
arr3d.shape
#通过np.newaxis可以进行轴的添加

(4, 1, 4)

In [55]:
arr = np.random.randn(3,4,5)
depth_means = arr.mean(2)
print(depth_means.shape)
depth_means

(3, 4)


array([[-0.14547935, -0.61594014, -0.14080415, -0.42396552],
       [ 0.35368529, -0.32293734, -0.21593901,  0.16666992],
       [-0.43747388,  0.35689748, -0.27977821,  0.03877312]])

In [56]:
demeaned2 = arr-depth_means[:,:,np.newaxis]
print(demeaned2.mean(2))
demeaned2
#验证得到 是进行了广播行为 完成了矩平化

[[ 2.22044605e-17 -4.44089210e-17  2.22044605e-17 -4.44089210e-17]
 [ 2.22044605e-17 -2.22044605e-17  1.11022302e-17  6.66133815e-17]
 [ 3.33066907e-17 -4.44089210e-17  0.00000000e+00  0.00000000e+00]]


array([[[ 0.63494971,  0.8861108 , -0.90316782, -0.88624152,
          0.26834883],
        [-0.11672944,  0.19840283,  0.8191057 ,  0.67225765,
         -1.57303674],
        [-0.21164569, -0.5837272 , -0.63472756,  1.2820709 ,
          0.14802956],
        [ 1.08562675, -0.76160766, -0.94925543,  1.2704091 ,
         -0.64517276]],

       [[-0.43461945,  0.67695798, -0.47364411,  0.36563939,
         -0.1343338 ],
        [ 0.19289978,  0.55700477,  0.08092581, -0.82320327,
         -0.00762709],
        [ 0.10878121, -1.28480818, -0.25728166,  1.28955082,
          0.14375781],
        [ 0.47793865,  1.33350707, -1.02732952,  0.10480638,
         -0.88892257]],

       [[-0.51591026,  0.05802051,  0.15602538,  0.60953775,
         -0.30767338],
        [-0.82232745,  0.43399065, -0.06403477, -1.07636256,
          1.52873411],
        [ 0.40126713, -1.16462457,  1.24544317, -0.1340077 ,
         -0.34807803],
        [ 1.37095411, -0.26970661, -0.33798058,  0.86328794,
         -1

In [57]:
arr = np.zeros((4,3))
arr[:] = 5
arr
#可以通过广播进行数组值的设置

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [58]:
#ufunc方法 简洁的循环方法
arr = np.arange(10)
np.add.reduce(arr)

45

In [59]:
#acculate和reduce就像cumsum和sum的关系
#它产生一个跟数组大小相同的累计
arr = np.arange(15).reshape((3,5))
np.add.accumulate(arr,axis=1)
#得到了累加的过程

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [60]:
#outer用于计算两个数组的叉积
arr = np.arange(3).repeat([1,2,2])
arr

array([0, 1, 1, 2, 2])

In [61]:
np.multiply.outer(arr,np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [ ]:
#之前所有的ndarray是相同的数据类型：dtype
#但是可以定义结构化ndarray
#结构化 C中的struct 可以的

In [62]:
dtype = [('x',np.float64),('y',np.int32)]
sarr = np.array([(1.5,6),(np.pi,-2)],dtype=dtype)
sarr
#显示定义dtype之后 每个元素都是一个结构体 对象数据类型按照定义的顺序进行

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [63]:
print(sarr[0])
print(sarr[0]['y'])
#可以通过定义时的名称进行索引

(1.5, 6)
6


In [64]:
dtype = [('x',np.float64,3),('y',np.int32)]
arr = np.zeros(4,dtype=dtype)
arr
#定义了多维字段

array([([0., 0., 0.], 0), ([0., 0., 0.], 0), ([0., 0., 0.], 0),
       ([0., 0., 0.], 0)], dtype=[('x', '<f8', (3,)), ('y', '<i4')])

In [65]:
dtype = [('x',[('a','f8'),('b','f4')]),('y',np.int32)]
data = np.array([((1,2),5),((3,4),6)])
data
#使用了嵌套形式的dtype

array([[(1, 2), 5],
       [(3, 4), 6]], dtype=object)

In [67]:
#排序方法
arr = np.random.randn(6)
arr.sort()
arr
#sort进行排序

array([-1.05297122, -0.51631176, -0.34991311, -0.14948435, -0.10652187,
        1.36700145])

In [68]:
arr = np.random.randn(3,5)
arr

array([[-1.35236875,  0.36309135, -0.23043739,  0.65039695, -0.31242147],
       [ 0.23686882, -0.80417821,  0.7388366 ,  0.0393521 ,  0.90739913],
       [-1.02881417,  0.2284782 , -1.19902548, -0.13778005, -1.36215117]])

In [69]:
arr[:,0].sort()
arr
#如果sort作用于对象的一个视图上 原对象也会被修改

array([[-1.35236875,  0.36309135, -0.23043739,  0.65039695, -0.31242147],
       [-1.02881417, -0.80417821,  0.7388366 ,  0.0393521 ,  0.90739913],
       [ 0.23686882,  0.2284782 , -1.19902548, -0.13778005, -1.36215117]])

In [75]:
#与之相反的是np.sort是会创建一个副本 对副本进行排序 对原样本没有影响
arr = np.random.randn(5)
arr

array([ 1.18394614, -1.08713977,  0.45138142,  0.43098959, -0.87090775])

In [71]:
print(np.sort(arr))
arr

[-2.34824072 -0.55778142  0.36770613  1.54043507  1.95367701]


array([-2.34824072,  1.95367701, -0.55778142,  0.36770613,  1.54043507])

In [81]:
#值得注意的是没有降序操作 不过可以升序排序再反过来即可
print(np.sort(arr))
np.sort(arr)[::-1]
#即为降序

[-1.08713977 -0.87090775  0.43098959  0.45138142  1.18394614]


array([ 1.18394614,  0.45138142,  0.43098959, -0.87090775, -1.08713977])

In [83]:
#间接排序
values = np.array([5,0,1,3,2])
indexer = values.argsort()
print(indexer)
values[indexer]
#获得的是表示顺序的索引位置

[1 2 4 3 0]


array([0, 1, 2, 3, 5])

In [84]:
arr = np.random.randn(3,5)
arr[0] = values
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [ 1.02105816,  0.72347247, -0.97226951, -1.48290334,  0.96967941],
       [-0.42835948,  0.61001378,  0.5510164 ,  0.63670246,  0.57692951]])

In [85]:
arr[:,arr[0].argsort()]
#索引排序是可以用来进行取值

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [ 0.72347247, -0.97226951,  0.96967941, -1.48290334,  1.02105816],
       [ 0.61001378,  0.5510164 ,  0.57692951,  0.63670246, -0.42835948]])

In [88]:
first_name = np.array(['Bob','Jane','Steve','Bill','Barbara'])
last_name = np.array(['Jones','Arnold','Arnold','Jone','Walters'])
sorter = np.lexsort((first_name,last_name))
list(zip(last_name[sorter],first_name[sorter]))
#lexsort可以对多个键进行间接排序

[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jone', 'Bill'),
 ('Jones', 'Bob'),
 ('Walters', 'Barbara')]

In [89]:
#searchsorted 在有序数组中查找元素位置 二分法！
arr = np.array([0,1,7,12,15])
arr.searchsorted(9)
#获得索引位置 返回相等值组的左侧索引

3

In [93]:
data = np.floor(np.random.uniform(0,10000,size=50))
bins = np.array([0,100,1000,5000,10000])
data

array([4304., 2097., 6064., 9600., 9013., 9561., 6768.,   53., 2537.,
       1473., 4482., 1754., 1461., 1341., 2261.,  531.,  831., 2755.,
       8361., 5799.,  857., 4669., 4409., 2258.,  628., 4143., 7592.,
       6738., 6761., 2324., 8143., 8975., 4093., 5771., 5056., 6544.,
       3901., 3062., 1649., 7414., 7537., 7358., 1571., 1790., 2559.,
       7147., 5551., 6248.,  872., 5519.])

In [94]:
#为了得到所属区间的编号 可以使用searchsorted 1就代表[0,100)以此类推
labels = bins.searchsorted(data)
labels

array([3, 3, 4, 4, 4, 4, 4, 1, 3, 3, 3, 3, 3, 3, 3, 2, 2, 3, 4, 4, 2, 3,
       3, 3, 2, 3, 4, 4, 4, 3, 4, 4, 3, 4, 4, 4, 3, 3, 3, 4, 4, 4, 3, 3,
       3, 4, 4, 4, 2, 4], dtype=int64)

In [95]:
from pandas import Series
Series(data).groupby(labels).size()
#之后可以通过groupby进行分组了

1     1
2     5
3    22
4    22
dtype: int64

In [ ]:
'''
#性能建议：
1.将python循环和条件逻辑转化为数组运算和布尔数组运算
2.尽量使用广播
3.避免复制数据，尽量使用数组视图（切片）
4.利用ufunc及各种方法
如果碰到值得注意
'''

